### ISSUE TITLE
Impossible d'installer le package depuis Package Control.

### ISSUE THREAD

**Issue by wmai** [Globidev/Sublime-Text-42-Headers#12]
Package info was unavailable last time crawler ran. Error downloading repository. HTTP error 404 downloading https://api.github.com/repos/Globicodeur/Sublime-Text-42-Headers.

**Comment by Globidev** [comment]
Yay, I changed my username on Github sorry :(
I'll fix this when I have time :+1:

**Comment by Globidev** [comment]
https://github.com/wbond/package_control_channel/pull/4581

**Comment by Globidev** [comment]
It's merged so It should be back to normal
