### ISSUE TITLE
Possibility to change user name

### ISSUE THREAD

**Issue by elieteyssedou** [Globidev/Sublime-Text-42-Headers#16]
It would be great if we could change user name directly from sublime.

I explain myself: on my personal computer (not on *42* computers), my user name is *"Elie"*, but my user name at *42* is *"eteyssed"*.

So I'm having things like *"Elie@student.42.fr"* instead of *"eteyssed@student.42.fr"*.

What do you think about that ? :smiley:

**Comment by Globidev** [comment]
There is now a configuration file (accessible via the `42 headers: settings` command)
It's a json configuration file and supports the key `login` that you can change
