### ISSUE TITLE
Could not change username + header does not toogle

### ISSUE THREAD

**Issue by clerty** [Globidev/Sublime-Text-42-Headers#20]
ST 3.2.2
log:
`reloading settings Packages/User/42-headers.sublime-settings
Traceback (most recent call last):
  File "/Users/clerty/Library/Application Support/Sublime Text 3/Packages/42
Headers/settings.py", line 21, in update_login
    Settings.LOGIN_KEY,
AttributeError: 'NoneType' object has no attribute 'LOGIN_KEY'`
42-headers.sublime-settings:
`{
	"login": "my42login"
}`
Could you please tell, is there a mistake anywhere? And could it be a reason why header does not toogle?

**Comment by Globidev** [comment]
That looks like a strange error. I can't seem to be able to reproduce.
Could you tell me a bit more about your environment ? Could you check the python version in the sublime console for instance ? (`sys.version`)

**Comment by clerty** [comment]
Python 2.7.16
macOS Catalina 10.15.4 on VMWare Workstation Player 15
so, it actually started to work by itself (no reboot, reinstall, etc.). Maybe it's all because that's a virtual machine
anyway, thanks for great plugin!
